############################################
####     XSync Site-level Settings      ####
############################################
siteSettings:
    kind: tabs
    label: Xsync Configuration
    meta:
        restricted: XsyncAdministrator
        tabGroups:
            xsyncConfig: XSync Site Level Configuration
    contents:
        connectionManagement:
            kind: tab
            label: Connection Management
            group: xsyncConfig
            active: true
            contents:
                connectionManagementPanel:
                    kind: panel.form
                    name: connectionManagementPanel
                    label: Connection Management
                    footer: false
                    contents:
                        httpsEnabled:
                            kind: panel.input.switchbox
                            name: httpsEnabled
                            label: Enable HTTPS Transfers?
                            onText: Enabled
                            offText: Disabled
                            description: >
                                Use HTTPS for transfers? This is the default configuration. To turn off this setting, another method of transfers must be turned on.
                        asperaEnabled:
                            kind: panel.input.switchbox
                            name: asperaEnabled
                            label: Enable Aspera Transfers?
                            onText: Enabled
                            offText: Disabled
                            description: >
                                Use Aspera for transfers?  This requires a valid Aspera server to receive files.
                        xsyncConnectionManagerScript:
                            tag: script|src="~/scripts/xnat-plugins/xsyncPlugin/admin/xsyncConnectionManager.js"
        configurationDashboard:
            kind: tab
            label: Configuration Dashboard
            group: xsyncConfig
            active: true
            contents:
                configurationDashboardPanel:
                    kind: panel.form
                    name: configurationDashboardPanel
                    label: Configuration Dashboard
                    footer: false
                    contents:
                        xsyncConfigurationDashboardTable:
                            tag: "div#xsync-configuration-dashboard-panel"
                        xsyncConnectionManagerScript:
                            tag: script|src="~/scripts/xnat-plugins/xsyncPlugin/admin/xsyncConfigurationDashboard.js"
        remoteTokenRefresh:
            kind: tab
            label: Remote Token
            group: xsyncConfig
            active: false
            contents:
                remoteTokenRefreshPanel:
                    kind: panel.form
                    name: remoteTokenRefreshPanel
                    label: Remote Token Refresh
                    method: POST
                    url: /xapi/xsyncSitePreferences # url to save data
                    contentType: application/json # submits json as text
                    contents:
                        tokenRefreshInterval:
                            kind: panel.input.text
                            label: Token Refresh Interval
                            description: >
                                Interval for running token refresh service specified in hours or minutes.  Must be 5 minutes or greater.  Uses
                                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.
                                <b>NOTE&#58;  This setting requires Tomcat restart to take effect.</b>
        syncRetry:
            kind: tab
            label: Sync Retry
            group: xsyncConfig
            active: false
            contents:
                syncRetryPanel:
                    kind: panel.form
                    name: syncRetryPanel
                    label: Sync Retry Settings
                    method: POST
                    url: /xapi/xsyncSitePreferences
                    contentType: application/json
                    contents:
                        syncRetryInterval:
                            kind: panel.input.text
                            label: Retry Interval
                            description: >
                                Interval between retry on sync failure. Must be 5 minutes or greater. Uses
                                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.
                                <b>NOTE&#58;  This setting requires Tomcat restart to take effect.</b>
                        syncRetryCount:
                            kind: panel.input.text
                            label: Max Retries
                            description: Number of times sync is retried before going to a failed state.
        maxUncompressedZipFileSize:
            kind: tab
            label: Maximum Total Uncompressed File Size
            group: xsyncConfig
            active: false
            contents:
                maxUncompressedZipFileSizePanel:
                    kind: panel.form
                    name: maxUncompressedZipFileSizePanel
                    label: Max. Total Uncompressed File Size Settings
                    method: POST
                    url: /xapi/xsyncSitePreferences
                    contentType: application/json
                    contents:
                        fileSizeHelptext:
                            tag: div.message
                            content: >
                                Xsync compresses resources before sync. When a resource at any level -- Project, Subject, or Experiment -- remains large after compression, 
                                syncing to a destination XNAT may fail. When this parameter is set to a value other than -1, then for a large resource, Xsync will 
                                generate multiple zip files, each not exceeding the configured max size. The default value -1 disables this behavior, 
                                meaning a single zip file will be synced.
                            after: >
                                <br/>
                        syncMaxUncompressedZipFileSize:
                            kind: panel.input.text
                            label: Max. Total Uncompressed File Size
                            validation: required integer
                            description: >
                                Maximum total size of files in a zip (before compression) in bytes, -1 means no limit. 
                                If a resource to be synced is larger than this value, multiple zips will be sent (none to exceed this size).
        whitelistSiteTab:
            kind: tab
            label: Whitelist Of Accepted Receiving XNATs
            group: xsyncConfig
            active: false
            contents:
                whitelistSitePanel:
                    kind: panel
                    name: whitelistSitePanel
                    label: Whitelist Of Accepted Receiving XNATs
                    footer: false
                    contents:
                        limitToWhitelist:
                            kind: panel.input.switchbox
                            name: limitToWhitelist
                            value: false
                            label: Enable Site Whitelisting?
                            onText: Enabled
                            offText: Disabled
                            description: >
                                If turned on, users will only be able to export data to one of a set of pre-approved XNAT sites using Xsync.
                                Users will always be able to use Xsync to transmit data within this XNAT.
                        xsyncWhitelistTable:
                            tag: "div#xsync-whitelist-table"
                        xsyncWhitelistScript:
                            tag: script|src="~/scripts/xnat-plugins/xsyncPlugin/admin/xsyncWhitelistManager.js"
                        xsyncWhitelistCss:
                            tag: link|rel="stylesheet"|type="text/css"|href="~/style/xnat-plugins/xsyncPlugin/xsync-whitelist.css"
        projectBlacklist:
            kind: tab
            label: Project Blacklist
            group: xsyncConfig
            active: true
            contents:
                projectBlacklistPanel:
                    kind: panel.form
                    name: projectBlacklistPanel
                    label: Project Blacklist
                    footer: false
                    contents:
                        xsyncProjectBlacklistTable:
                            tag: "div#xsync-project-blacklist-panel"
                        xsyncProjectBlacklistScript:
                            tag: script|src="~/scripts/xnat-plugins/xsyncPlugin/admin/xsyncProjectBlacklistManager.js"
        asperaDefaults:
            kind: tab
            label: Aspera Server Defaults
            group: xsyncConfig
            active: false
            contents:
                asperaPanel:
                    kind: panel.form
                    name: asperaPanel
                    label: Aspera Server Defaults
                    method: POST
                    url: /xapi/xsyncSitePreferences/aspera 
                    contentType: json 
                    contents:
                        message:
                            tag: div.message.bold
                            content: >
                                NOTICE: This panel sets default Aspera connection settings.  These site-level 
                                settings may be useful if one of your destination sites supports Aspera-based
                                XSync sends and multiple projects will connect to the same Aspera server, as these
                                will become the default settings for project connections.  <b>Please note, however, that
                                XSync Aspera settings must be configured and enabled for each project.</b>
                        asperaNodeUrl:
                            kind: panel.input.text
                            name: asperaNodeUrl
                            label: Aspera Node
                            description: >
                                The node name of the Aspera server
                        asperaNodeUser:
                            kind: panel.input.text
                            name: asperaNodeUser
                            label: Aspera User
                            description: >
                                The the username used to connect to the Aspera server
                        privateKey:
                            kind: panel.input.text
                            name: privateKey
                            label: Private Key Location
                            size: 30
                            description: >
                                The location of the private key used to connect to the server
                        destinationDirectory:
                            kind: panel.input.text
                            name: destinationDirectory
                            label: Remote Destination Directory
                            size: 30
                            description: >
                                The remote directory to which the files will be sent
                        logDirectory:
                            kind: panel.input.text
                            name: logDirectory
                            label: Log Directory
                            size: 30
                            placeholder: /tmp/
                            description: >
                                The local directory used for logging
                        sshPort:
                            kind: panel.input.text
                            name: sshPort
                            label: SSH Port
                            placeholder: 22
                            description: >
                                The remote server's SSH port
                        udpPort:
                            kind: panel.input.text
                            name: udpPort
                            placeholder: 33001
                            description: >
                                The remote server's UDP port
