############################################
####     XSync Site-level Settings      ####
############################################
siteSettings:
    kind: tabs
    label: Xsync Configuration
    meta:
        tabGroups:
            xsyncConfig: XSync Site Level Configuration
    contents:
        remoteTokenRefresh:
            kind: tab
            label: Remote Token
            group: xsyncConfig
            active: true
            contents:
                remoteTokenRefreshPanel:
                    kind: panel.form
                    name: remoteTokenRefreshPanel
                    label: Remote Token Refresh
                    method: POST
                    url: /xapi/xsyncSitePreferences # url to save data
                    contentType: text/json # submits json as text
                    contents:
                        tokenRefreshInterval:
                            kind: panel.input.text
                            label: Token Refresh Interval
                            description: >
                                Interval for running token refresh service specified in hours or minutes.  Must be 5 minutes or greater.  Uses
                                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.
                                <b>NOTE&#58;  This setting requires Tomcat restart to take effect.</b>
        syncRetry:
            kind: tab
            label: Sync Retry
            group: xsyncConfig
            active: false
            contents:
                syncRetryPanel:
                    kind: panel.form
                    name: syncRetryPanel
                    label: Sync Retry Settings
                    method: POST
                    url: /xapi/xsyncSitePreferences
                    contentType: text/json
                    contents:
                        syncRetryInterval:
                            kind: panel.input.text
                            label: Retry Interval
                            description: >
                                Interval between retry on sync failure. Must be 5 minutes or greater. Uses
                                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.
                                <b>NOTE&#58;  This setting requires Tomcat restart to take effect.</b>
                        syncRetryCount:
                            kind: panel.input.text
                            label: Max Retries
                            description: Number of times sync is retried before going to a failed state.
        asperaDefaults:
            kind: tab
            label: Aspera Server Defaults
            group: xsyncConfig
            active: false
            contents:
                asperaPanel:
                    kind: panel.form
                    name: asperaPanel
                    label: Aspera Server Defaults
                    method: POST
                    url: /xapi/xsyncSitePreferences/aspera 
                    contentType: json 
                    contents:
                        message:
                            tag: div.message.bold
                            content: >
                                NOTICE: This panel sets default Aspera connection settings.  These site-level 
                                settings may be useful if one of your destination sites supports Aspera-based
                                XSync sends and multiple projects will connect to the same Aspera server, as these
                                will become the default settings for project connections.  <b>Please note, however, that
                                XSync Aspera settings must be configured and enabled for each project.</b> 
                        asperaNodeUrl:
                            kind: panel.input.text
                            name: asperaNodeUrl
                            label: Aspera Node
                            description: >
                                The node name of the Aspera server
                        asperaNodeUser:
                            kind: panel.input.text
                            name: asperaNodeUser
                            label: Aspera User
                            description: >
                                The the username used to connect to the Aspera server
                        privateKey:
                            kind: panel.input.text
                            name: privateKey
                            label: Private Key Location
                            size: 30
                            description: >
                                The location of the private key used to connect to the server
                        destinationDirectory:
                            kind: panel.input.text
                            name: destinationDirectory
                            label: Remote Destination Directory
                            size: 30
                            description: >
                                The remote directory to which the files will be sent
                        logDirectory:
                            kind: panel.input.text
                            name: logDirectory
                            label: Log Directory
                            size: 30
                            placeholder: /tmp/
                            description: >
                                The local directory used for logging
                        sshPort:
                            kind: panel.input.text
                            name: sshPort
                            label: SSH Port
                            placeholder: 22
                            description: >
                                The remote server's SSH port
                        udpPort:
                            kind: panel.input.text
                            name: udpPort
                            placeholder: 33001
                            description: >
                                The remote server's UDP port
        cliTransferDefaults:
            kind: tab
            label: CLI Transfer Client Settings
            group: xsyncConfig
            active: false
            contents:
                cliTransferPanel:
                    kind: panel.form
                    name: cliTransferPanel
                    label: XSync CLI Transfer Client Settings
                    method: POST
                    url: /xapi/xsyncSitePreferences/cliTransfer 
                    contentType: json 
                    contents:
                        message:
                            tag: div.message.bold
                            content: >
                                NOTICE: This sets default CLI Transfer Client settings.  These site-level 
                                settings may be useful if one of your destination sites supports CLI client transfers
                                and multiple projects will connect to the same CLI client script, as these
                                will become the default settings for project connections.  <b>Please note, however, that
                                CLI client settings must be configured and enabled for each project.</b>
                        cliTransferScript:
                            kind: panel.input.text
                            name: cliTransferScript
                            label: CLI Client Script
                            description: >
                                The path to the transfer client script
                        cliTransferHost:
                            kind: panel.input.text
                            name: cliTransferHost
                            label: CLI Client Host
                            description: >
                                The host the client sends to (supplied via the --host parameter)
                        cliTransferUser:
                            kind: panel.input.text
                            name: cliTransferUser
                            label: CLI Client User
                            description: >
                                The username sends to (supplied via the --user parameter)
                        cliTransferRemoteDir:
                            kind: panel.input.text
                            name: cliTransferRemoteDir
                            label: Remote Destination Directory
                            size: 30
                            description: >
                                (OPTIONAL) The remote directory to which the files will be sent (supplied via the --rdir parameter)
                        cliTransferPrivateKey:
                            kind: panel.input.text
                            name: cliTransferPrivateKey
                            label: Private Key Location
                            size: 30
                            description: >
                                (OPTIONAL)  The location of the private key used to connect to the server (supplied via the --key parameter)
