org.nrg.Role=XsyncAdministrator
org.nrg.Role.XsyncAdministrator.key=XsyncAdministrator
org.nrg.Role.XsyncAdministrator.name=Xsync Administrator
org.nrg.Role.XsyncAdministrator.warning=WARNING: This role gives the user permission to view, change, remove, or create all Xsync connections across the entire site.
org.nrg.Role.XsyncAdministrator.description=A user with Xsync Administrator role can manage all Xsync connections throughout the site.