def pluginVersion = '1.3.2-SNAPSHOT'

group 'org.nrg.xsync'
version pluginVersion

def vXnatDev = '1.7.4'
def vXnat = '1.7.4'
def vXnatTasks = '1.7.0'
def vMizer = '1.0-SNAPSHOT'
def vJunit = '4.12'
def vSpring = '4.2.9.RELEASE'
def vSlf4j = '1.7.25'
def vLog4j = '1.2.17'
def vSpringSecurity = '4.0.4.RELEASE'
def vSwagger = '2.4.0'

apply plugin: 'groovy'
apply plugin: 'maven'
apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'idea'
apply plugin: 'eclipse'
apply plugin: 'xnat-data-builder'

buildscript {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://nrgxnat.artifactoryonline.com/nrgxnat/libs-release'
            name 'XNAT Release Repository'
        }
        maven {
            url 'https://nrgxnat.artifactoryonline.com/nrgxnat/libs-snapshot'
            name 'XNAT Snapshot Repository'
        }
    }
    dependencies {
        classpath "org.nrg.xnat.build:xnat-data-builder:1.7.1-SNAPSHOT"
    }
}

repositories {
    mavenLocal()
    maven {
        url 'https://nrgxnat.artifactoryonline.com/nrgxnat/libs-release'
        name 'XNAT Release Repository'
    }
    maven {
        url 'https://nrgxnat.artifactoryonline.com/nrgxnat/libs-snapshot'
        name 'XNAT Snapshot Repository'
    }
    maven {
        url 'https://nrgxnat.artifactoryonline.com/nrgxnat/ext-release'
        name 'XNAT External Release Repository'
    }
    mavenCentral()
    jcenter()
    maven {
        url 'http://www.dcm4che.org/maven2'
        name 'Dcm4che Repository'
    }
}

// Use this configuration to put dependencies into the fat jar
configurations {
    compile.extendsFrom(compileAndInclude)
}

task fatJar(type: Jar) {
    zip64 true
    baseName = project.name + '-all'
    from {
        configurations.compileAndInclude.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}

sourceCompatibility = 1.7
targetCompatibility = 1.7

if (hasProperty("rt.17.jar")) {
    // Solution for bootstrap classpath warning and possible issues with compatibility with 1.7 libraries
    // was taken from this post on discuss.gradle.org: http://bit.ly/24xD9j0
    def rt17jar = getProperty("rt.17.jar")
    logger.info "Using ${rt17jar} as the bootstrap class path jar."
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.fork = true
            options.compilerArgs << "-XDignore.symbol.file"
            options.bootClasspath = rt17jar
        }
    }
} else {
    logger.warn "No value was set for the rt.17.jar build property, using the default bootstrap class path. You should consider setting rt.17.jar to indicate a jar file containing the Java 1.7 run-time library:\n"
    logger.warn "  ./gradlew -Prt.17.jar=rt-1.7.0_45.jar war\n"
}

dependencies {
    compile("org.nrg.xnat:web:${vXnatDev}") {
        transitive = false
    }
    compile("org.nrg.xnat:xnat-data-models:${vXnatDev}") {
        transitive = false
    }
   // compile "org.nrg.xdat:tasks:${vXnatTasks}"

    compile("org.nrg.xdat:core:${vXnatDev}") {
        transitive = false
    }
    compile("org.nrg:framework:${vXnat}") {
        transitive = false
    }
    compile("org.nrg:config:${vXnat}") {
        transitive = false
    }
    compile("org.nrg:transaction:${vXnat}") {
        transitive = false
    }
    compile("org.nrg:mail:${vXnat}") {
        transitive = false
    }
    compile "org.nrg:prefs:${vXnatDev}"

    compile "org.nrg.dicom:mizer:${vMizer}"
    compile "org.nrg:DicomEdit:6.0.1"
    compile "org.nrg:dicomtools:${vXnatDev}"

    compile "org.reflections:reflections:0.9.10"
    compile "javax.servlet:javax.servlet-api:3.1.0"

    compile(group: 'turbine', name: 'turbine', version: '2.3.3') {
        exclude group: '*'
    }
    compile(group: 'org.apache.velocity', name: 'velocity', version: '1.7') {
        exclude group: '*'
    }
    compile "org.slf4j:slf4j-api:${vSlf4j}"
    compile "org.slf4j:slf4j-log4j12:${vSlf4j}"
    compile "org.slf4j:jul-to-slf4j:${vSlf4j}"
    compile "log4j:log4j:${vLog4j}"

    compile group: 'org.restlet', name: 'org.restlet', version:'1.1.10'
    compile group: 'commons-lang', name: 'commons-lang', version:'2.6'
    compile group: 'com.google.collections', name: 'google-collections', version:'1.0'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version:'2.2.3'
    compile group: 'org.apache.axis', name: 'axis', version:'1.4'
    compile group: 'javax.servlet', name: 'servlet-api', version:'2.5'
    compile group: 'org.codehaus.jackson', name: 'jackson-mapper-asl', version:'1.8.5'
    compile group: 'dcm4che', name: 'dcm4che-core', version:'2.0.25'
    compile "javax.mail:javax.mail-api:1.5.5"
    compile 'com.google.code.gson:gson:2.6.2'
    compile(group: 'stratum', name: 'stratum', version: '1.0') {
        exclude group: '*'
    }

    compile "eu.bitwalker:UserAgentUtils:1.20"

    compile "org.springframework:spring-aop:${vSpring}"
    compile "org.springframework:spring-beans:${vSpring}"
    compile "org.springframework:spring-context-support:${vSpring}"
    compile "org.springframework:spring-context:${vSpring}"
    compile "org.springframework:spring-core:${vSpring}"
    compile "org.springframework:spring-jdbc:${vSpring}"
    compile "org.springframework:spring-jms:${vSpring}"
    compile "org.springframework:spring-messaging:${vSpring}"
    compile "org.springframework:spring-orm:${vSpring}"
    compile "org.springframework:spring-oxm:${vSpring}"
    compile "org.springframework:spring-tx:${vSpring}"
    compile "org.springframework:spring-web:${vSpring}"
    compile "org.springframework:spring-webmvc:${vSpring}"

    compile "io.springfox:springfox-swagger2:${vSwagger}"
    compile "io.springfox:springfox-swagger-ui:${vSwagger}"

    compile "org.springframework.security:spring-security-acl:${vSpringSecurity}"
    compile "org.springframework.security:spring-security-aspects:${vSpringSecurity}"
    compile "org.springframework.security:spring-security-config:${vSpringSecurity}"
    compile "org.springframework.security:spring-security-ldap:${vSpringSecurity}"
    compile "org.springframework.security:spring-security-taglibs:${vSpringSecurity}"
    compile "org.springframework.ldap:spring-ldap-core:2.0.4.RELEASE"

    runtime "ecs:ecs:1.4.2"

    testCompile "junit:junit:${vJunit}"
    testCompile "org.springframework:spring-test:${vSpring}"
}
