#
# XSync logging
#
log4j.category.org.nrg.xsync=DEBUG, xsync
log4j.additivity.org.nrg.xsync=false


#
# XSync log output
#
log4j.appender.xsync=org.apache.log4j.DailyRollingFileAppender
log4j.appender.xsync.File=${xnat.home}/logs/xsync.log
log4j.appender.xsync.DatePattern='.'yyyy-MM-dd
log4j.appender.xsync.layout=org.apache.log4j.PatternLayout
log4j.appender.xsync.layout.ConversionPattern=%d %m%n
